LOST_IN_TRANSLATION = 6711
THERE_WILL_BE_BLOOD = 56782
TOKYO_STORY = 6643

# Tokyo Story top 3
IKIRU = 6669
LATE_SPRING = 42217
EARLY_SUMMER = 8785

TOKYO_STORY_SIMILAR_MOVIES = {IKIRU, LATE_SPRING, EARLY_SUMMER}

# Lost In Translation top 3
BROKEN_FLOWERS = 34437
IN_THE_MOOD_FOR_LOVE = 4144
PUNCH_DRUNK_LOVE = 5673  # Weird!

LOST_IN_TRANSLATION_SIMILAR_MOVIES = {BROKEN_FLOWERS, IN_THE_MOOD_FOR_LOVE, PUNCH_DRUNK_LOVE}

# There Will Be Blood top 3
NO_COUNTRY_FOR_OLD_MEN = 55820
TAXI_DRIVER = 111
OLD_BOY = 27773

THERE_WILL_BE_BLOOD_SIMILAR_MOVIES = {NO_COUNTRY_FOR_OLD_MEN, TAXI_DRIVER, OLD_BOY}